const mongoose = require('mongoose');
require('dotenv').config({ path: './config.env' });

// Import models
const House = require('./models/House');
const Resource = require('./models/Resource');

// Enhanced demo data with more comprehensive test data
const demoHouses = [
  {
    number: '1',
    street: 'Main Street',
    taleem: true,
    mashwara: false,
    notes: 'First house on main street - Active family',
    members: [
      {
        name: 'Ahmed Khan',
        fatherName: 'Abdul Khan',
        age: 45,
        gender: 'Male',
        occupation: 'Businessman',
        education: 'Graduate',
        quran: 'yes',
        maktab: 'no',
        dawat: '3-day',
        dawatCounts: {
          '3-day': 2,
          '10-day': 1,
          '40-day': 0,
          '4-month': 0,
        },
        mobile: '9876543210',
        role: 'Head',
      },
      {
        name: 'Fatima Khan',
        fatherName: 'Ahmed Khan',
        age: 40,
        gender: 'Female',
        occupation: 'Other',
        education: '12th',
        quran: 'yes',
        maktab: 'no',
        dawat: 'Nil',
        dawatCounts: {
          '3-day': 0,
          '10-day': 0,
          '40-day': 0,
          '4-month': 0,
        },
        mobile: '9876543211',
        role: 'Member',
      },
      {
        name: 'Ali Khan',
        fatherName: 'Ahmed Khan',
        age: 12,
        gender: 'Male',
        occupation: 'Child',
        education: 'Below 8th',
        quran: 'no',
        maktab: 'yes',
        dawat: 'Nil',
        dawatCounts: {
          '3-day': 0,
          '10-day': 0,
          '40-day': 0,
          '4-month': 0,
        },
        mobile: '',
        role: 'Member',
      },
    ],
  },
  {
    number: '2',
    street: 'Main Street',
    taleem: false,
    mashwara: true,
    notes: 'Second house with mashwara activities',
    members: [
      {
        name: 'Mohammed Ali',
        fatherName: 'Hassan Ali',
        age: 50,
        gender: 'Male',
        occupation: 'Farmer',
        education: '10th',
        quran: 'yes',
        maktab: 'no',
        dawat: '10-day',
        dawatCounts: {
          '3-day': 1,
          '10-day': 3,
          '40-day': 1,
          '4-month': 0,
        },
        mobile: '9876543212',
        role: 'Head',
      },
      {
        name: 'Aisha Ali',
        fatherName: 'Mohammed Ali',
        age: 15,
        gender: 'Female',
        occupation: 'Student',
        education: '10th',
        quran: 'yes',
        maktab: 'no',
        dawat: '3-day',
        dawatCounts: {
          '3-day': 1,
          '10-day': 0,
          '40-day': 0,
          '4-month': 0,
        },
        mobile: '9876543213',
        role: 'Member',
      },
    ],
  },
  {
    number: '3',
    street: 'Park Road',
    taleem: true,
    mashwara: true,
    notes: 'House with both taleem and mashwara - Religious family',
    members: [
      {
        name: 'Abdul Rahman',
        fatherName: 'Saleem Rahman',
        age: 55,
        gender: 'Male',
        occupation: 'Ulma',
        education: 'Above Graduate',
        quran: 'yes',
        maktab: 'no',
        dawat: '40-day',
        dawatCounts: {
          '3-day': 5,
          '10-day': 3,
          '40-day': 2,
          '4-month': 1,
        },
        mobile: '9876543214',
        role: 'Head',
      },
      {
        name: 'Zara Rahman',
        fatherName: 'Abdul Rahman',
        age: 25,
        gender: 'Female',
        occupation: 'Student',
        education: 'Graduate',
        quran: 'yes',
        maktab: 'no',
        dawat: '10-day',
        dawatCounts: {
          '3-day': 2,
          '10-day': 1,
          '40-day': 0,
          '4-month': 0,
        },
        mobile: '9876543215',
        role: 'Member',
      },
      {
        name: 'Yusuf Rahman',
        fatherName: 'Abdul Rahman',
        age: 8,
        gender: 'Male',
        occupation: 'Child',
        education: 'Below 8th',
        quran: 'no',
        maktab: 'yes',
        dawat: 'Nil',
        dawatCounts: {
          '3-day': 0,
          '10-day': 0,
          '40-day': 0,
          '4-month': 0,
        },
        mobile: '',
        role: 'Member',
      },
    ],
  },
  {
    number: '4',
    street: 'Park Road',
    taleem: false,
    mashwara: false,
    notes: 'New family - Recently moved in',
    members: [
      {
        name: 'Hassan Ahmed',
        fatherName: 'Ibrahim Ahmed',
        age: 35,
        gender: 'Male',
        occupation: 'Worker',
        education: '12th',
        quran: 'no',
        maktab: 'no',
        dawat: 'Nil',
        dawatCounts: {
          '3-day': 0,
          '10-day': 0,
          '40-day': 0,
          '4-month': 0,
        },
        mobile: '9876543216',
        role: 'Head',
      },
      {
        name: 'Sara Ahmed',
        fatherName: 'Hassan Ahmed',
        age: 30,
        gender: 'Female',
        occupation: 'Other',
        education: '10th',
        quran: 'no',
        maktab: 'no',
        dawat: 'Nil',
        dawatCounts: {
          '3-day': 0,
          '10-day': 0,
          '40-day': 0,
          '4-month': 0,
        },
        mobile: '9876543217',
        role: 'Member',
      },
    ],
  },
  {
    number: '5',
    street: 'School Street',
    taleem: true,
    mashwara: false,
    notes: 'Family near school - Education focused',
    members: [
      {
        name: 'Omar Farooq',
        fatherName: 'Farooq Ahmed',
        age: 42,
        gender: 'Male',
        occupation: 'Shopkeeper',
        education: '12th',
        quran: 'yes',
        maktab: 'no',
        dawat: '4-month',
        dawatCounts: {
          '3-day': 3,
          '10-day': 2,
          '40-day': 1,
          '4-month': 1,
        },
        mobile: '9876543218',
        role: 'Head',
      },
      {
        name: 'Layla Farooq',
        fatherName: 'Omar Farooq',
        age: 18,
        gender: 'Female',
        occupation: 'Student',
        education: '12th',
        quran: 'yes',
        maktab: 'no',
        dawat: '3-day',
        dawatCounts: {
          '3-day': 1,
          '10-day': 0,
          '40-day': 0,
          '4-month': 0,
        },
        mobile: '9876543219',
        role: 'Member',
      },
      {
        name: 'Ahmad Farooq',
        fatherName: 'Omar Farooq',
        age: 10,
        gender: 'Male',
        occupation: 'Child',
        education: 'Below 8th',
        quran: 'no',
        maktab: 'yes',
        dawat: 'Nil',
        dawatCounts: {
          '3-day': 0,
          '10-day': 0,
          '40-day': 0,
          '4-month': 0,
        },
        mobile: '',
        role: 'Member',
      },
    ],
  },
  {
    number: '6',
    street: 'College Road',
    taleem: true,
    mashwara: true,
    notes: 'Academic family - Both parents are teachers',
    members: [
      {
        name: 'Dr. Khalid Hussain',
        fatherName: 'Mohammed Hussain',
        age: 48,
        gender: 'Male',
        occupation: 'Teacher',
        education: 'Above Graduate',
        quran: 'yes',
        maktab: 'no',
        dawat: '40-day',
        dawatCounts: {
          '3-day': 4,
          '10-day': 2,
          '40-day': 1,
          '4-month': 0,
        },
        mobile: '9876543220',
        role: 'Head',
      },
      {
        name: 'Dr. Amina Hussain',
        fatherName: 'Khalid Hussain',
        age: 45,
        gender: 'Female',
        occupation: 'Teacher',
        education: 'Above Graduate',
        quran: 'yes',
        maktab: 'no',
        dawat: '10-day',
        dawatCounts: {
          '3-day': 2,
          '10-day': 1,
          '40-day': 0,
          '4-month': 0,
        },
        mobile: '9876543221',
        role: 'Member',
      },
      {
        name: 'Ibrahim Hussain',
        fatherName: 'Khalid Hussain',
        age: 20,
        gender: 'Male',
        occupation: 'Student',
        education: 'Graduate',
        quran: 'yes',
        maktab: 'no',
        dawat: '3-day',
        dawatCounts: {
          '3-day': 1,
          '10-day': 0,
          '40-day': 0,
          '4-month': 0,
        },
        mobile: '9876543222',
        role: 'Member',
      },
      {
        name: 'Mariam Hussain',
        fatherName: 'Khalid Hussain',
        age: 16,
        gender: 'Female',
        occupation: 'Student',
        education: '12th',
        quran: 'yes',
        maktab: 'no',
        dawat: 'Nil',
        dawatCounts: {
          '3-day': 0,
          '10-day': 0,
          '40-day': 0,
          '4-month': 0,
        },
        mobile: '9876543223',
        role: 'Member',
      },
    ],
  },
  {
    number: '7',
    street: 'Market Street',
    taleem: false,
    mashwara: false,
    notes: 'Business family - Owns multiple shops',
    members: [
      {
        name: 'Rashid Merchant',
        fatherName: 'Ahmed Merchant',
        age: 52,
        gender: 'Male',
        occupation: 'Businessman',
        education: 'Graduate',
        quran: 'yes',
        maktab: 'no',
        dawat: '4-month',
        dawatCounts: {
          '3-day': 6,
          '10-day': 4,
          '40-day': 2,
          '4-month': 1,
        },
        mobile: '9876543224',
        role: 'Head',
      },
      {
        name: 'Noor Merchant',
        fatherName: 'Rashid Merchant',
        age: 47,
        gender: 'Female',
        occupation: 'Other',
        education: '12th',
        quran: 'yes',
        maktab: 'no',
        dawat: '10-day',
        dawatCounts: {
          '3-day': 2,
          '10-day': 1,
          '40-day': 0,
          '4-month': 0,
        },
        mobile: '9876543225',
        role: 'Member',
      },
      {
        name: 'Usman Merchant',
        fatherName: 'Rashid Merchant',
        age: 22,
        gender: 'Male',
        occupation: 'Businessman',
        education: 'Graduate',
        quran: 'yes',
        maktab: 'no',
        dawat: '3-day',
        dawatCounts: {
          '3-day': 1,
          '10-day': 0,
          '40-day': 0,
          '4-month': 0,
        },
        mobile: '9876543226',
        role: 'Member',
      },
    ],
  },
  {
    number: '8',
    street: 'Hospital Road',
    taleem: true,
    mashwara: true,
    notes: 'Medical professionals family',
    members: [
      {
        name: 'Dr. Salman Khan',
        fatherName: 'Abdul Khan',
        age: 38,
        gender: 'Male',
        occupation: 'Doctor',
        education: 'Above Graduate',
        quran: 'yes',
        maktab: 'no',
        dawat: '10-day',
        dawatCounts: {
          '3-day': 3,
          '10-day': 2,
          '40-day': 0,
          '4-month': 0,
        },
        mobile: '9876543227',
        role: 'Head',
      },
      {
        name: 'Dr. Fatima Khan',
        fatherName: 'Salman Khan',
        age: 35,
        gender: 'Female',
        occupation: 'Doctor',
        education: 'Above Graduate',
        quran: 'yes',
        maktab: 'no',
        dawat: '3-day',
        dawatCounts: {
          '3-day': 1,
          '10-day': 0,
          '40-day': 0,
          '4-month': 0,
        },
        mobile: '9876543228',
        role: 'Member',
      },
      {
        name: 'Zainab Khan',
        fatherName: 'Salman Khan',
        age: 6,
        gender: 'Female',
        occupation: 'Child',
        education: 'Below 8th',
        quran: 'no',
        maktab: 'yes',
        dawat: 'Nil',
        dawatCounts: {
          '3-day': 0,
          '10-day': 0,
          '40-day': 0,
          '4-month': 0,
        },
        mobile: '',
        role: 'Member',
      },
    ],
  },
  {
    number: '9',
    street: 'Factory Lane',
    taleem: false,
    mashwara: false,
    notes: 'Working class family',
    members: [
      {
        name: 'Javed Iqbal',
        fatherName: 'Iqbal Ahmed',
        age: 41,
        gender: 'Male',
        occupation: 'Worker',
        education: '10th',
        quran: 'no',
        maktab: 'no',
        dawat: 'Nil',
        dawatCounts: {
          '3-day': 0,
          '10-day': 0,
          '40-day': 0,
          '4-month': 0,
        },
        mobile: '9876543229',
        role: 'Head',
      },
      {
        name: 'Nasreen Iqbal',
        fatherName: 'Javed Iqbal',
        age: 38,
        gender: 'Female',
        occupation: 'Other',
        education: 'Below 8th',
        quran: 'no',
        maktab: 'no',
        dawat: 'Nil',
        dawatCounts: {
          '3-day': 0,
          '10-day': 0,
          '40-day': 0,
          '4-month': 0,
        },
        mobile: '9876543230',
        role: 'Member',
      },
      {
        name: 'Imran Iqbal',
        fatherName: 'Javed Iqbal',
        age: 14,
        gender: 'Male',
        occupation: 'Student',
        education: '10th',
        quran: 'no',
        maktab: 'no',
        dawat: 'Nil',
        dawatCounts: {
          '3-day': 0,
          '10-day': 0,
          '40-day': 0,
          '4-month': 0,
        },
        mobile: '9876543231',
        role: 'Member',
      },
    ],
  },
  {
    number: '10',
    street: 'Masjid Street',
    taleem: true,
    mashwara: true,
    notes: 'Religious family - Near masjid',
    members: [
      {
        name: 'Maulana Abdul Qadir',
        fatherName: 'Qadir Hussain',
        age: 60,
        gender: 'Male',
        occupation: 'Ulma',
        education: 'Above Graduate',
        quran: 'yes',
        maktab: 'no',
        dawat: '4-month',
        dawatCounts: {
          '3-day': 8,
          '10-day': 5,
          '40-day': 3,
          '4-month': 2,
        },
        mobile: '9876543232',
        role: 'Head',
      },
      {
        name: 'Hafiz Mohammed',
        fatherName: 'Abdul Qadir',
        age: 28,
        gender: 'Male',
        occupation: 'Hafiz',
        education: '12th',
        quran: 'yes',
        maktab: 'no',
        dawat: '40-day',
        dawatCounts: {
          '3-day': 4,
          '10-day': 2,
          '40-day': 1,
          '4-month': 0,
        },
        mobile: '9876543233',
        role: 'Member',
      },
      {
        name: 'Ayesha Qadir',
        fatherName: 'Abdul Qadir',
        age: 55,
        gender: 'Female',
        occupation: 'Other',
        education: '10th',
        quran: 'yes',
        maktab: 'no',
        dawat: '10-day',
        dawatCounts: {
          '3-day': 2,
          '10-day': 1,
          '40-day': 0,
          '4-month': 0,
        },
        mobile: '9876543234',
        role: 'Member',
      },
      {
        name: 'Bilal Qadir',
        fatherName: 'Abdul Qadir',
        age: 9,
        gender: 'Male',
        occupation: 'Child',
        education: 'Below 8th',
        quran: 'no',
        maktab: 'yes',
        dawat: 'Nil',
        dawatCounts: {
          '3-day': 0,
          '10-day': 0,
          '40-day': 0,
          '4-month': 0,
        },
        mobile: '',
        role: 'Member',
      },
    ],
  },
  {
    number: '11',
    street: 'Engineering Colony',
    taleem: true,
    mashwara: false,
    notes: 'Engineering professionals family',
    members: [
      {
        name: 'Engr. Faisal Ahmed',
        fatherName: 'Ahmed Ali',
        age: 44,
        gender: 'Male',
        occupation: 'Engineer',
        education: 'Above Graduate',
        quran: 'yes',
        maktab: 'no',
        dawat: '3-day',
        dawatCounts: {
          '3-day': 2,
          '10-day': 1,
          '40-day': 0,
          '4-month': 0,
        },
        mobile: '9876543235',
        role: 'Head',
      },
      {
        name: 'Engr. Sana Ahmed',
        fatherName: 'Faisal Ahmed',
        age: 40,
        gender: 'Female',
        occupation: 'Engineer',
        education: 'Above Graduate',
        quran: 'yes',
        maktab: 'no',
        dawat: 'Nil',
        dawatCounts: {
          '3-day': 0,
          '10-day': 0,
          '40-day': 0,
          '4-month': 0,
        },
        mobile: '9876543236',
        role: 'Member',
      },
      {
        name: 'Hassan Ahmed',
        fatherName: 'Faisal Ahmed',
        age: 17,
        gender: 'Male',
        occupation: 'Student',
        education: '12th',
        quran: 'yes',
        maktab: 'no',
        dawat: 'Nil',
        dawatCounts: {
          '3-day': 0,
          '10-day': 0,
          '40-day': 0,
          '4-month': 0,
        },
        mobile: '9876543237',
        role: 'Member',
      },
    ],
  },
  {
    number: '12',
    street: 'Free Colony',
    taleem: false,
    mashwara: false,
    notes: 'Family with free occupation',
    members: [
      {
        name: 'Rahman Ali',
        fatherName: 'Ali Hassan',
        age: 33,
        gender: 'Male',
        occupation: 'Free',
        education: '12th',
        quran: 'no',
        maktab: 'no',
        dawat: 'Nil',
        dawatCounts: {
          '3-day': 0,
          '10-day': 0,
          '40-day': 0,
          '4-month': 0,
        },
        mobile: '9876543238',
        role: 'Head',
      },
      {
        name: 'Khadija Ali',
        fatherName: 'Rahman Ali',
        age: 29,
        gender: 'Female',
        occupation: 'Free',
        education: '10th',
        quran: 'no',
        maktab: 'no',
        dawat: 'Nil',
        dawatCounts: {
          '3-day': 0,
          '10-day': 0,
          '40-day': 0,
          '4-month': 0,
        },
        mobile: '9876543239',
        role: 'Member',
      },
    ],
  },
];

const demoResources = [
  {
    title: 'Quran Learning Guide',
    description: 'Complete guide for learning Quran with proper tajweed rules',
    category: 'PDF',
    fileUrl: '/uploads/quran-guide.pdf',
    fileName: 'quran-guide.pdf',
    fileSize: 2048576,
    fileType: 'application/pdf',
    tags: ['Quran', 'Learning', 'Tajweed'],
    isPublic: true,
    uploadedBy: 'admin',
  },
  {
    title: 'Islamic Calendar 2024',
    description:
      'Complete Islamic calendar with prayer times and important dates',
    category: 'Document',
    fileUrl: '/uploads/islamic-calendar-2024.docx',
    fileName: 'islamic-calendar-2024.docx',
    fileSize: 1048576,
    fileType:
      'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    tags: ['Calendar', 'Prayer Times', '2024'],
    isPublic: true,
    uploadedBy: 'admin',
  },
  {
    title: 'Masjid Architecture Design',
    description: 'Modern masjid design concepts and architectural guidelines',
    category: 'Image',
    fileUrl: '/uploads/masjid-design.jpg',
    fileName: 'masjid-design.jpg',
    fileSize: 3145728,
    fileType: 'image/jpeg',
    tags: ['Architecture', 'Design', 'Masjid'],
    isPublic: true,
    uploadedBy: 'admin',
  },
  {
    title: 'Islamic Education Resources',
    description:
      'Collection of Islamic education materials for children and adults',
    category: 'Link',
    fileUrl: 'https://example.com/islamic-education',
    fileName: '',
    fileSize: 0,
    fileType: 'link',
    tags: ['Education', 'Islamic', 'Resources'],
    isPublic: true,
    uploadedBy: 'admin',
  },
  {
    title: 'Community Management Guide',
    description: 'Best practices for managing masjid community and events',
    category: 'PDF',
    fileUrl: '/uploads/community-guide.pdf',
    fileName: 'community-guide.pdf',
    fileSize: 1572864,
    fileType: 'application/pdf',
    tags: ['Community', 'Management', 'Guide'],
    isPublic: true,
    uploadedBy: 'admin',
  },
  {
    title: 'Dawat-e-Islami Guidelines',
    description:
      'Complete guidelines for Dawat-e-Islami activities and programs',
    category: 'PDF',
    fileUrl: '/uploads/dawat-guidelines.pdf',
    fileName: 'dawat-guidelines.pdf',
    fileSize: 3072000,
    fileType: 'application/pdf',
    tags: ['Dawat', 'Islami', 'Guidelines'],
    isPublic: true,
    uploadedBy: 'admin',
  },
  {
    title: 'Prayer Times Audio',
    description: 'Audio recordings of prayer times and adhan',
    category: 'Audio',
    fileUrl: '/uploads/prayer-times.mp3',
    fileName: 'prayer-times.mp3',
    fileSize: 5242880,
    fileType: 'audio/mpeg',
    tags: ['Prayer', 'Audio', 'Adhan'],
    isPublic: true,
    uploadedBy: 'admin',
  },
  {
    title: 'Islamic Lectures Video Series',
    description: 'Video series of Islamic lectures and sermons',
    category: 'Video',
    fileUrl: '/uploads/islamic-lectures.mp4',
    fileName: 'islamic-lectures.mp4',
    fileSize: 104857600,
    fileType: 'video/mp4',
    tags: ['Lectures', 'Video', 'Islamic'],
    isPublic: true,
    uploadedBy: 'admin',
  },
  {
    title: 'Masjid Budget Template',
    description: 'Excel template for masjid budget planning and management',
    category: 'Document',
    fileUrl: '/uploads/masjid-budget.xlsx',
    fileName: 'masjid-budget.xlsx',
    fileSize: 2097152,
    fileType:
      'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    tags: ['Budget', 'Template', 'Excel'],
    isPublic: true,
    uploadedBy: 'admin',
  },
  {
    title: 'Islamic Calligraphy Collection',
    description: 'Beautiful collection of Islamic calligraphy and artwork',
    category: 'Image',
    fileUrl: '/uploads/calligraphy-collection.jpg',
    fileName: 'calligraphy-collection.jpg',
    fileSize: 4194304,
    fileType: 'image/jpeg',
    tags: ['Calligraphy', 'Art', 'Islamic'],
    isPublic: true,
    uploadedBy: 'admin',
  },
];

// Connect to MongoDB
const connectDB = async () => {
  try {
    await mongoose.connect(process.env.MONGODB_URI, {
      useNewUrlParser: true,
      useUnifiedTopology: true,
    });
    console.log('✅ MongoDB Connected for seeding');
  } catch (error) {
    console.error('❌ MongoDB connection error:', error.message);
    process.exit(1);
  }
};

// Seed data function
const seedData = async () => {
  try {
    console.log('🌱 Starting to seed data...');

    // Clear existing data
    await House.deleteMany({});
    await Resource.deleteMany({});
    console.log('🗑️ Cleared existing data');

    // Insert houses
    const savedHouses = await House.insertMany(demoHouses);
    console.log(`🏠 Inserted ${savedHouses.length} houses`);

    // Insert resources
    const savedResources = await Resource.insertMany(demoResources);
    console.log(`📚 Inserted ${savedResources.length} resources`);

    console.log('✅ Data seeding completed successfully!');
    console.log(`📊 Total Houses: ${savedHouses.length}`);
    console.log(`📊 Total Resources: ${savedResources.length}`);

    // Show some statistics
    const totalMembers = savedHouses.reduce(
      (total, house) => total + house.members.length,
      0,
    );
    console.log(`👥 Total Members: ${totalMembers}`);

    process.exit(0);
  } catch (error) {
    console.error('❌ Error seeding data:', error);
    process.exit(1);
  }
};

// Run the seeding
connectDB().then(() => {
  seedData();
});
